apiVersion: v1
kind: Service
metadata:
  name: enriqueta
  namespace: 04josecama
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8080
      nodePort: 30001
  selector:
    app: enriqueta
