apiVersion: v1
kind: Service
metadata:
  name: enriqueta-frontend
  namespace: 04josecama
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: enriqueta-frontend
