apiVersion: apps/v1
kind: Deployment
metadata:
  name: enriqueta-frontend
  namespace: 04josecama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enriqueta-frontend
  template:
    metadata:
      labels:
        app: enriqueta-frontend
    spec:
      containers:
      - name: enriqueta-frontend
        image: jmegun/enriqueta-fe:latest
        resources:
          requests:
            cpu: "125m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
        ports:
        - containerPort: 80
